### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by erbridge** [limetext/lime-backend#73]
From https://travis-ci.org/limetext/lime-backend/jobs/67430883:

```
panic: sync: negative WaitGroup counter
goroutine 13 [running]:
sync.(*WaitGroup).Add(0xc20800a660, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:67 +0x96
sync.(*WaitGroup).Done(0xc20800a660)
	/usr/local/go/src/sync/waitgroup.go:85 +0x31
github.com/limetext/lime-backend/lib/watch.(*dummy).FileChanged(0xc20800a640, 0x659650, 0x11)
	/home/travis/gopath/src/github.com/limetext/lime-backend/lib/watch/watch_test.go:63 +0xaf
github.com/limetext/lime-backend/lib/watch.(*Watcher).apply(0xc2080a22d0, 0x659650, 0x11, 0x2)
	github.com/limetext/lime-backend/lib/watch/_test/_obj_test/watch.go:323 +0x234
github.com/limetext/lime-backend/lib/watch.func·001()
	github.com/limetext/lime-backend/lib/watch/_test/_obj_test/watch.go:262 +0xb9
github.com/limetext/lime-backend/lib/watch.(*Watcher).Observe(0xc2080a22d0)
	github.com/limetext/lime-backend/lib/watch/_test/_obj_test/watch.go:299 +0x1a2
created by github.com/limetext/lime-backend/lib/watch.TestObserve
	/home/travis/gopath/src/github.com/limetext/lime-backend/lib/watch/watch_test.go:308 +0x1b2
goroutine 1 [chan receive]:
testing.RunTests(0x6930d0, 0x744d00, 0x11, 0x11, 0x747001)
	/usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20803c0f0, 0x74d9c0)
	/usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/limetext/lime-backend/lib/watch/_test/_testmain.go:132 +0x291
goroutine 12 [runnable]:
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc2080a2280)
	/home/travis/gopath/src/gopkg.in/fsnotify.v1/inotify.go:253 +0xa16
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/travis/gopath/src/gopkg.in/fsnotify.v1/inotify.go:58 +0x32b
goroutine 11 [runnable]:
sync.(*Mutex).Lock(0xc20800a678)
	/usr/local/go/src/sync/mutex.go:41
github.com/limetext/lime-backend/lib/watch.(*dummy).Text(0xc20800a640, 0x0, 0x0)
	/home/travis/gopath/src/github.com/limetext/lime-backend/lib/watch/watch_test.go:87 +0x46
github.com/limetext/lime-backend/lib/watch.TestObserve(0xc208068360)
	/home/travis/gopath/src/github.com/limetext/lime-backend/lib/watch/watch_test.go:315 +0x35a
testing.tRunner(0xc208068360, 0x744e20)
	/usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xa8b
```

**Comment by db47h** [comment]
Getting the same bug on Linux. Looks like FileChanged is fired twice:

```
015/07/13 12:58:58 CEST] [FNST] (github.com/limetext/lime-backend/lib/log.(*Logger).Finest:49) Watch(testdata/test.txt)
[2015/07/13 12:58:58 CEST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*Logger).Debug:57) Got FileChanged on testdata/test.txt
[2015/07/13 12:58:58 CEST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*Logger).Debug:57) Got FileChanged on testdata/test.txt
[2015/07/13 12:58:58 CEST] [EROR] (github.com/limetext/lime-backend/lib/log.(*Logger).Logf:105) Watcher error: %!s(<nil>)
```

When testing [similar code with fsnotify directly](https://gist.github.com/db47h/a34fb8f25222e3dff4c4), I'm getting two WRITE events as well. That's what's breaking the WaitGroup based logic for the tests.

The <nil> watcher errors occur after the watcher is closed. They are caused by the `w.wchr.Errors` channel being closed and the `err := <-w.wchr.Errors` read always succeeding with a nil value (same for `ev := <-w.wchr.Events` BTW). Changing the assignments to `foo, ok := <- bar` in Observer should help with that.

**Comment by db47h** [comment]
Also why not exiting the Observe for loop if any of the wchr channels are closed?

Tentative fix for both issues:

https://github.com/db47h/lime-backend/commit/b07e2f93665eaee2aa55c8bfc701566849f6ae46

**Comment by quarnster** [comment]
@db47h, LGTM, could you submit a PR please?

**Comment by db47h** [comment]
Done. Wasn't too sure if exiting Observe() was a good idea, but if the channels are closed, I don't really see another option. Also documented Observe(), never hurts ;)
