### ISSUE TITLE
[10/06/15 13:03:42] [EROR] Failed to register command nop: Command wasn't registered in any list: nop

### ISSUE THREAD

**Issue by remexre** [limetext/lime-backend#79]
When I try to run the tests as specified on [the Building page](https://github.com/limetext/lime/wiki/Building) (`go test github.com/limetext/lime-backend/lib/...`), I get an error:

```
[10/06/15 13:10:21] [EROR] Failed to register command nop: Command wasn't registered in any list: nop
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x478 pc=0x478]

runtime stack:
runtime.throw(0x371ea8, 0x2a)
	/usr/lib/go/src/runtime/panic.go:527 +0x78
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x44

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1d05c, 0x10647ba4, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:120 +0x11c fp=0x10647b84 sp=0x10647b6c
github.com/limetext/gopy/lib._Cfunc_Py_InitializeEx(0x0)
	??:0 +0x30 fp=0x10647ba0 sp=0x10647b84
github.com/limetext/gopy/lib.initAndLock(0x0, 0x18)
	/home/nathan/go/src/github.com/limetext/gopy/lib/lock.go:60 +0xd8 fp=0x10647bc4 sp=0x10647ba0
github.com/limetext/gopy/lib.InitAndLock(0x10670990)
	/home/nathan/go/src/github.com/limetext/gopy/lib/lock.go:42 +0x20 fp=0x10647bd0 sp=0x10647bc4
github.com/limetext/lime-backend/lib/sublime.init.1()
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/sublime/sublime_manual.go:74 +0x250 fp=0x10647f68 sp=0x10647bd0
github.com/limetext/lime-backend/lib/sublime.init()
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/sublime/sublime_test.go:192 +0x930 fp=0x10647f98 sp=0x10647f68
main.init()
	github.com/limetext/lime-backend/lib/sublime/_test/_testmain.go:60 +0x58 fp=0x10647f9c sp=0x10647f98
runtime.main()
	/usr/lib/go/src/runtime/proc.go:100 +0x274 fp=0x10647fc4 sp=0x10647f9c
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm.s:1036 +0x4 fp=0x10647fc4 sp=0x10647fc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 19 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0x10666180, 0xb4f782a0, 0x1066a090)
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:27 +0x6c
created by github.com/limetext/log4go.NewConsoleLogWriter
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:19 +0x74

goroutine 20 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0x106661c0, 0xb4f782a0, 0x1066a090)
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:27 +0x6c
created by github.com/limetext/log4go.NewConsoleLogWriter
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:19 +0x74

goroutine 21 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0x106860f4)
	/home/nathan/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x48
created by github.com/limetext/text.(*SerializedBuffer).init
	/home/nathan/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd0

goroutine 22 [syscall]:
syscall.Syscall6(0xfc, 0x4, 0x1085bdac, 0x7, 0xffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/asm_linux_arm.s:48 +0x8
syscall.EpollWait(0x4, 0x1085bdac, 0x7, 0x7, 0xffffffff, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_arm.go:365 +0x90
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0x1066e640, 0x3a1c00, 0x0, 0x0)
	/home/nathan/go/src/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0x84
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0x106722a0)
	/home/nathan/go/src/gopkg.in/fsnotify.v1/inotify.go:179 +0x1e8
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/nathan/go/src/gopkg.in/fsnotify.v1/inotify.go:58 +0x2c8

goroutine 23 [chan receive]:
github.com/limetext/lime-backend/lib/log.NewLogWriter.func1(0x1066e660, 0x1066a360)
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/log/logwriter.go:37 +0x44
created by github.com/limetext/lime-backend/lib/log.NewLogWriter
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/log/logwriter.go:40 +0xa0

goroutine 24 [chan receive]:
github.com/limetext/lime-backend/lib.(*Editor).inputthread(0x10670990)
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/editor.go:366 +0xa4
created by github.com/limetext/lime-backend/lib.GetEditor
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/editor.go:142 +0x900

goroutine 25 [select]:
github.com/limetext/lime-backend/lib/watch.(*Watcher).Observe(0x106722d0)
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/watch/watch.go:201 +0x240
created by github.com/limetext/lime-backend/lib.GetEditor
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/editor.go:143 +0x924
FAIL	github.com/limetext/lime-backend/lib/sublime	0.106s
```

**Comment by tikiking1** [comment]
At least one problem: `NopApplicationCommand` doesn't actually implement `ApplicationCommand`; it's missing `IsChecked()`.

**Comment by tikiking1** [comment]
Fixing that,
```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x478 pc=0x478]

runtime stack:
runtime.throw(0x371ed0, 0x2a)
	/usr/lib/go/src/runtime/panic.go:527 +0x78
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:12 +0x44

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x1d05c, 0x10657ba4, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:120 +0x11c fp=0x10657b84 sp=0x10657b6c
github.com/limetext/gopy/lib._Cfunc_Py_InitializeEx(0x0)
	??:0 +0x30 fp=0x10657ba0 sp=0x10657b84
github.com/limetext/gopy/lib.initAndLock(0x0, 0x18)
	/home/nathan/go/src/github.com/limetext/gopy/lib/lock.go:60 +0xd8 fp=0x10657bc4 sp=0x10657ba0
github.com/limetext/gopy/lib.InitAndLock(0x10666990)
	/home/nathan/go/src/github.com/limetext/gopy/lib/lock.go:42 +0x20 fp=0x10657bd0 sp=0x10657bc4
github.com/limetext/lime-backend/lib/sublime.init.1()
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/sublime/sublime_manual.go:74 +0x250 fp=0x10657f68 sp=0x10657bd0
github.com/limetext/lime-backend/lib/sublime.init()
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/sublime/sublime_test.go:192 +0x930 fp=0x10657f98 sp=0x10657f68
main.init()
	github.com/limetext/lime-backend/lib/sublime/_test/_testmain.go:60 +0x58 fp=0x10657f9c sp=0x10657f98
runtime.main()
	/usr/lib/go/src/runtime/proc.go:100 +0x274 fp=0x10657fc4 sp=0x10657f9c
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm.s:1036 +0x4 fp=0x10657fc4 sp=0x10657fc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_arm.s:1036 +0x4

goroutine 5 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0x10616240, 0xb5fc02b8, 0x1060a0d0)
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:27 +0x6c
created by github.com/limetext/log4go.NewConsoleLogWriter
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:19 +0x74

goroutine 6 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0x10616280, 0xb5fc02b8, 0x1060a0d0)
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:27 +0x6c
created by github.com/limetext/log4go.NewConsoleLogWriter
	/home/nathan/go/src/github.com/limetext/log4go/termlog.go:19 +0x74

goroutine 7 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0x10610284)
	/home/nathan/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x48
created by github.com/limetext/text.(*SerializedBuffer).init
	/home/nathan/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd0

goroutine 8 [syscall]:
syscall.Syscall6(0xfc, 0x4, 0x108a7dac, 0x7, 0xffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/asm_linux_arm.s:48 +0x8
syscall.EpollWait(0x4, 0x108a7dac, 0x7, 0x7, 0xffffffff, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_arm.go:365 +0x90
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0x1060e750, 0x3a1c00, 0x0, 0x0)
	/home/nathan/go/src/gopkg.in/fsnotify.v1/inotify_poller.go:85 +0x84
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0x10612390)
	/home/nathan/go/src/gopkg.in/fsnotify.v1/inotify.go:179 +0x1e8
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/nathan/go/src/gopkg.in/fsnotify.v1/inotify.go:58 +0x2c8

goroutine 9 [chan receive]:
github.com/limetext/lime-backend/lib/log.NewLogWriter.func1(0x1060e770, 0x1060a3a0)
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/log/logwriter.go:37 +0x44
created by github.com/limetext/lime-backend/lib/log.NewLogWriter
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/log/logwriter.go:40 +0xa0

goroutine 10 [chan receive]:
github.com/limetext/lime-backend/lib.(*Editor).inputthread(0x10666990)
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/editor.go:366 +0xa4
created by github.com/limetext/lime-backend/lib.GetEditor
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/editor.go:142 +0x900

goroutine 11 [select]:
github.com/limetext/lime-backend/lib/watch.(*Watcher).Observe(0x106123c0)
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/watch/watch.go:201 +0x240
created by github.com/limetext/lime-backend/lib.GetEditor
	/home/nathan/go/src/github.com/limetext/lime-backend/lib/editor.go:143 +0x924
FAIL	github.com/limetext/lime-backend/lib/sublime	0.101s
```

**Comment by erbridge** [comment]
I can't reproduce this locally. What are your `go` and `python` versions?

**Comment by erbridge** [comment]
I can't reproduce this locally. What are your `go` and `python` versions?

**Comment by tikiking1** [comment]
```
$ go version
go version go1.5.1 linux/arm
$ python --version
Python 3.5.0
$ python2 --version
Python 2.7.10
```

**Comment by zoli** [comment]
Is this still happening?
